#! /bin/sh
bspc rule -r "*"


#AUTOSTART
nm-applet &
xrdb ~/.Xresources &
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9

#GLOBALSETTINGS
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#Colors
bspc config normal_border_color "#44475a"
bspc config focused_border_color "#bd93f9"
bspc config active_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config top_padding 20
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0
bspc config border_width         2
bspc config window_gap          5


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


feh --bg-fill ~/Bilder/wallpaper.png
$HOME/.config/polybar/launch.sh



bspc rule -a Zathura state=tiled
bspc rule -a java-lang-Thread state=floating
bspc rule -a Welcome to Android Studio state=floating
bspc rule -a soffice.bin state=floating
bspc rule -a mpv state=pseudo_tiled
